style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/highercomve/GhostPen
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - docs
        - ci
        - build
        - chore
        - test
        - style
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      docs: Documentation
      ci: Continuous Integration
      build: Build System
      chore: Chores
      test: Tests
      style: Styles
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
